// ============================================
// Combat and attack config
// ============================================

const COMBAT_CONFIG = {
    attack: {
        punch: {
            damage: 7,
            knockback: 80,
            range: 65,
            rangeY: 65,
            cooldown: 280,
            activeFrames: 120,
            startup: 60,
            hitstun: 250,
            hitColor: 0xffee22,
        },
        kick: {
            damage: 13,
            knockback: 150,
            range: 85,
            rangeY: 80,
            cooldown: 480,
            activeFrames: 140,
            startup: 100,
            hitstun: 380,
            hitColor: 0xff6633,
        },
        rising: {
            damage: 18,
            knockback: 60,
            range: 70,
            rangeY: 160,
            cooldown: 600,
            activeFrames: 280,
            startup: 70,
            hitstun: 500,
            hitColor: 0xff9900,
            riseVY: -600,
        },
        airpunch: {
            damage: 10,
            knockback: 200,
            range: 80,
            rangeY: 70,
            cooldown: 300,
            activeFrames: 130,
            startup: 55,
            hitstun: 300,
            hitColor: 0x88ffee,
        },
        airkick: {
            damage: 16,
            knockback: 100,
            range: 70,
            rangeY: 120,
            cooldown: 420,
            activeFrames: 150,
            startup: 80,
            hitstun: 450,
            hitColor: 0xff44aa,
            downwardKB: true,
        },
        super: {
            damage: 28,
            knockback: 220,
            range: 110,
            rangeY: 110,
            dashVx: 380,
            cooldown: 900,
            activeFrames: 220,
            startup: 150,
            hitstun: 650,
            hitColor: 0xffffff,
        },
    },
    blockReduction: 0.15,
    rage: {
        max: 100,
        superCost: 100,
        superEnabled: false,
        onHit: 5,
        onGetHit: 9,
        onBlock: 4,
        onKick: 7,
        onRising: 12,
        onAirHit: 8,
        onSuper: 18,
    },
    attackNames: {
        punch: '拳击',
        kick: '踢击',
        rising: '升龙拳!!',
        airpunch: '飞拳',
        airkick: '飞脚',
        super: '超必杀!!',
    },
    attackTypes: {
        PUNCH: 'punch',
        KICK: 'kick',
        RISING: 'rising',
        AIR_PUNCH: 'airpunch',
        AIR_KICK: 'airkick',
        SUPER: 'super',
    },
    attackStates: {
        IDLE: 'idle',
        STARTUP: '_startup',
        ACTIVE: '_active',
        RECOVERY: '_recovery',
    }
};